version: 0.0.{build}

os: Visual Studio 2015

before_build:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - nuget restore Conduit.sln -DisableParallelProcessing

build:
  parallel: true

after_build:
  msbuild build /t:TestAll