# If this stops working, for example before_bukld is ignored, you may have to reuthenticate with github, https://ci.appveyor.com/account.
# See: http://help.appveyor.com/discussions/problems/6547-before_build-step-not-running

version: 0.0.{build}

os: Previous Visual Studio 2015

test: off

before_build:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - nuget restore Conduit.sln -DisableParallelProcessing

build:
  parallel: true

after_build:
  msbuild build.xml /t:TestAll /p:reporter=appveyor
